name: dmcca.be
markdown: redcarpet
pygments: true

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  gzip: false

destination: public
exclude: ["CNAME", "Rakefile", "README.md", "public"]
