source 'https://rubygems.org'
ruby '2.0.0'

gem 'liquid'
gem 'rack-jekyll'
gem 'jekyll-asset-pipeline', git: 'https://github.com/matthodan/jekyll-asset-pipeline'
gem 'compass'
gem 'zurb-foundation', git: 'https://github.com/dpmccabe/foundation', branch: 'bundled-v.5.0.2'
gem 'yui-compressor'
gem 'powder'
